name: Build
on:
  push:
    branches:
      - main

jobs:
  secops:
    name: SecOps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies # Instala dependencias y librerías necesarias
        run: |
          pip install pip-audit
          python -m venv .venv
          source .venv/bin/activate
          python - m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dependency Security Check
        run: |
          export PIPAPI_PYTHON_LOCATION=/home/runner/work/DevSecOps/DevSecOps/.venv/bin/python
          pip-audit
        continue-on-error: true

      - name: SonarCloud Scan # Ejecuta un análsis en SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=src

      - name: Zip Code # Genera un artefacto para Python
        run: |
          mkdir artifacts
          zip -r artifacts/streamlit.zip ./src ./.venv ./.streamlit

      - name: Publish Artifact # Publica el artefacto
        uses: actions/upload-artifact@v2
        with:
          name: streamlit-secops
          path: artifacts/streamlit.zip